export enum actionTypes {
  INIT_GAMES = "INIT_GAMES",

  IMPORT_FILE = "IMPORT_FILE",
  IMPORT_FILE_ERROR = "IMPORT_FILE_ERROR",

  LOAD_JSON_INFORMATION = "LOAD_JSON_INFORMATION",
  LOAD_GAMES_INFORMATION = "LOAD_GAMES_INFORMATION",
  LOAD_WISH_LIST_INFORMATION = "LOAD_WISH_LIST_INFORMATION",

  SET_INFORMATION_FILTER = "SET_INFORMATION_FILTER",
  SET_INFORMATION_FILTER_SUCCESS = "SET_INFORMATION_FILTER_SUCCESS",
  SET_TAB = "SET_TAB",

  SHORT_DATA_BY_NAME = "SHORT_DATA_BY_NAME",
  SHORT_DATA_BY_NAME_SUCCESS = "SHORT_DATA_BY_NAME_SUCCESS",

  RESET_FILTERED_VALUES = "RESET_FILTERED_VALUES",

  TOGGLE_DRAWER = "TOGGLE_DRAWER",
}
