env:
  browser: true
  es2021: true
  jest: true
extends:
  - plugin:react/recommended
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {
  import/no-named-as-default: off,
  no-bitwise: off,
  no-shadow: off,
  react/jsx-filename-extension: off,
  react/forbid-prop-types: off,
  react/no-array-index-key: off,
  react/prefer-stateless-function: off
}
